---
abstract: 'Preserve parts of the url'
author:
  - 'Jan Henning Thorsen'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-UrlWith
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojolicious-Plugin-UrlWith
  homepage: http://search.cpan.org/dist/Mojolicious-Plugin-UrlWith
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/mojolicious-plugin-urlwith
version: 0.0501
